# Nom de l'application
spring.application.name=Security_Stock

# ? Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/security_stock_db
spring.datasource.username=postgres
spring.datasource.password=hanae
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ? Port de l'application
server.port=8096

# Configuration Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Pour Spring Boot 3
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

jwt.refresh-token.expiration=604800000
rsa.publickey=classpath:keys/publicKey.pem
rsa.privatekey=classpath:keys/privateKey.pem

# Encoding
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent_output=true